exclude: "docs|node_modules|migrations|.tox|^.git$|venv"
default_stages: [commit, push]
fail_fast: true
default_language_version:
    python: python3.10

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: trailing-whitespace
      - id: detect-aws-credentials
        args: ["--allow-missing-credentials"]
        exclude: "api/config.yml|api/testdata/config.yml"
      - id: end-of-file-fixer
      - id: check-yaml
        exclude: "ecs-params*|helm*"
      - id: check-merge-conflict

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: 'v0.5.1'  # Use the latest version
    hooks:
      - id: ruff
        args: [ --fix, --exit-non-zero-on-fix ]

  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
        args: [--config, ./pyproject.toml]

  - repo: https://github.com/timothycrosley/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: ["--settings-file=./pyproject.toml"]



# sets up .pre-commit-ci.yaml to ensure pre-commit dependencies stay up to date
ci:
  autoupdate_schedule: weekly
  skip: []
  submodules: false
