[tool.ruff]
ignore = ["E501", "E211"]
line-length = 9999
per-file-ignores = {"__init__.py" = ["F401"]}
select = ["E", "F", "W"]
exclude = [
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".hg",
    ".mypy_cache",
    ".nox",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    "venv",
]

[tool.black]
line-length = 88
target-version = ['py310']
include = '\.pyi?$'
extend-exclude = '''
/(
  # directories
  \.eggs
  | \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | build
  | dist
)/
'''

[tool.isort]
profile = "black"
line_length = 88
multi_line_output = 3
default_section = "THIRDPARTY"
skip = ["venv/"]
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
